service: 'web-scraper-project'

package:
  exclude:
    - 'node_modules/**'
    - '.venv/**'
    - 'venv/**'
    - '*.pyc'
    - '*.ipynb'
    - '.vscode/**'
    - 'data/**'
    - 'sample.yml'
    - 'package-lock.json'
    - 'package.json'

provider:
  name: aws
  stage: dev
  region: ca-central-1
  timeout: 15

  apiGateway:
    binaryMediaTypes:
      - '*/*'


functions:
  api:
    runtime: python3.10
    handler: src/api/server.handler

    environment:
      POSTGRES_USER: ${env:POSTGRES_USER}
      POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
      POSTGRES_DB: ${env:POSTGRES_DB}
      POSTGRES_HOST: ${env:POSTGRES_HOST}
      POSTGRES_PORT: ${env:POSTGRES_PORT}

plugins:
  - serverless-python-requirements

# custom:
#   pythonRequirements:
#     pythonBin: ./.venv/bin/python
#     usePipenv: true