service: 'web-scraper-project'

package:
  exclude:
    - 'node_modules/**'
    - 'venv/**'
    - '*.pyc'
    - '*.ipynb'
    - '.vscode/**'
    - 'data/**'
    - 'sample.yml'
    - 'package-lock.json'
    - 'package.json'

provider:
  name: aws
  stage: dev
  region: ca-central-1
  timeout: 15

  apiGateway:
    binaryMediaTypes:
      - '*/*'

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
            - 's3-object-lambda:*'
            - 's3:ListBucket'
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
            - "s3:ListObject"

  environment:
    AWS_REGION_NAME: ca-central-1

functions:
  api:
    runtime: python3.10
    handler: src/api.server.handler

    environment:
      POSTGRES_USER: ${env:POSTGRES_USER}
      POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
      POSTGRES_DB: ${env:POSTGRES_DB}
      POSTGRES_HOST: ${env:POSTGRES_HOST}
      POSTGRES_PORT: ${env:POSTGRES_PORT}



plugins:
  - serverless-python-requirements