# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vmcortesf
service: 'web-scraper-project'

package:
  exclude:
    - 'node_modules/**'
    - '.venv/**'
    - 'venv/**'
    - '*.pyc'
    - '*.ipynb'
    - '.vscode/**'
    - 'data/**'
    - 'sample.yml'
    - 'package-lock.json'
    - 'package.json'
    - 'requirements.txt'
    - 'docker-compose.yml'
    - 'Makefile'
    - 'README.md'
    - '.env'
    - 'uv.lock'
    - 'pyproject.toml'
    - '.nvrc'
    - 'diagram.drawio'
    - 'env.sample'
    - '.python-version'
    - 'alembic.ini'
    - 'serverless.yml'
    - '.ruff_cache/**'
    - '__pycache__/**'

provider:
  name: aws
  stage: dev
  region: ca-central-1
  timeout: 15

  apiGateway:
    binaryMediaTypes:
      - '*/*'


functions:
  api:
    runtime: python3.10
    handler: src/api/server.handler

    events:
      - httpApi:
          path: /{proxy+}
          method: any

    environment:
      POSTGRES_USER: ${env:POSTGRES_USER}
      POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
      POSTGRES_DB: ${env:POSTGRES_DB}
      POSTGRES_HOST: ${env:POSTGRES_HOST}
      POSTGRES_PORT: ${env:POSTGRES_PORT}

plugins:
  - serverless-python-requirements

