"""Adding date to table

Revision ID: f5526aef18a2
Revises: 2c721c9f25c2
Create Date: 2025-08-13 11:39:10.061747

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5526aef18a2"
down_revision: Union[str, None] = "2c721c9f25c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("date_created", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "date_created")
    # ### end Alembic commands ###
