"""adding Client RFC

Revision ID: cd5f21ff9790
Revises: 77b65b33cafa
Create Date: 2025-08-08 10:43:38.320631

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd5f21ff9790"
down_revision: Union[str, None] = "77b65b33cafa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("rfc", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "clients", ["rfc"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clients", type_="unique")
    op.drop_column("clients", "rfc")
    # ### end Alembic commands ###
