"""Adding client name

Revision ID: 2c721c9f25c2
Revises: e2b475a43419
Create Date: 2025-08-13 09:52:23.513461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c721c9f25c2"
down_revision: Union[str, None] = "e2b475a43419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("client_name", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "client_name")
    # ### end Alembic commands ###
